language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9

install: yarn install

before_script: yarn build

script: yarn test:ci

after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js debug
